-- Generated by the database client.
CREATE TABLE category(
    category_id SERIAL NOT NULL,
    category_name varchar(50) NOT NULL,
    PRIMARY KEY(category_id)
);
INSERT INTO category(category_id,category_name) VALUES(1,'Personal'),(2,'News'),(3,'Entertainment'),(4,'Education'),(5,'Art and Design');





