-- Generated by the database client.
CREATE TABLE users(
    user_id SERIAL NOT NULL,
    first_name varchar(50) NOT NULL,
    middle_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    email varchar(50) NOT NULL,
    password text NOT NULL,
    date_joined timestamp without time zone NOT NULL DEFAULT now(),
    bio varchar(100),
    user_profile_image text,
    PRIMARY KEY(user_id)
);
CREATE UNIQUE INDEX users_email_key ON "users" USING btree ("email");
INSERT INTO users(user_id,first_name,middle_name,last_name,email,password,date_joined,bio,user_profile_image) VALUES(15,'Julliane','Julia','Tampus','julliane.tampus@carsu.edu.ph','$2b$10$qdb.8WQyR9G4OiHz4JRIluf.BBuCnp4U6.fG0dHgfCuf3NLsMuaDm','2023-12-05 04:32:46.212924',null,null),(7,'Julliane','Julia','Tampus','julliane.tampus123@gmail.com','$2b$10$vxar7FwMLiGs6EW/94IVWussF8H32ZLhKzgbtb15MgZK78dArYboW','2023-11-08 19:51:16.325524','--|Your code is okay 👍|--','1700793187467-d38f8db5-6765-44e2-9e3a-f3689c64c84c.jpg'),(5,'Lizel','Cambalon','Dacup','lizel.dacup@carsu.edu.ph','$2b$10$0FfqN075OjoXyMLAxAPjFu.s2fkWy94.oIDX0vvpV5raaFuxwB5Y.','2023-10-28 20:56:56.17933','haha','1701246439522-14aa461b-3cc5-44b2-8198-835d8c98a6e1.jpg');